### ISSUE TITLE
Doesn't reconnect after sleep mode or loss of connection for a long amount of time (usually more than 12 hours)

### ISSUE THREAD

**Issue by sorenbug** [StevenMattera/OJDS-NX#2]
I have to reboot to be able to connect again

**Comment by StevenMattera** [comment]
I'm not able to reproduce this issue on my switch. My switch has been sitting on my dock in sleep mode for the better part of the week, and OJD is still able to pick it up. However as a solution to your problem, so you don't have to restart everytime, if you put the attached config on to your SD card under the Kosmos Toolbox directory you will be able to start and stop OJDS-NX without having to restart your Switch.

[config.zip](https://github.com/StevenMattera/OJDS-NX/files/3456896/config.zip)
